<nav class="main-nav">
    <div class="nav-container">
        <a href="index.php" class="site-logo">
            <img src="images/logo.png" alt="SRN Careers Logo" width="80"> 
        </a>
        <input type="checkbox" id="menu-toggle" class="menu-toggle">
        <label for="menu-toggle" class="hamburger-menu" aria-label="Toggle Menu">
            <span></span>
            <span></span>
            <span></span>
        </label>
        
        <div class="nav-links">
            <a class="homenva" href="index.php">Home</a>
            <a href="jobs.php">Jobs</a>
            <a href="apply.php">Apply</a>
            <a href="about.php" class="active">About</a>
        </div>
        <a href="mailto:careers@srn.com" class="primary-button hideInMobile">Contact</a>
    </div>
</nav>