    <!-- Footer -->
    <footer class="main-footer">
        <div class="footer-container">
            <div class="footer-logo">
                <img src="images/logo.png" alt="SRN Careers Logo" width="80">
            </div>
            <div class="footers-links">
                <div class="footer-section">
                    <div>
                    <h4>Services</h4>
                    <a href="jobs.php">Executive Search</a>
                    <a href="jobs.php">Contract Staffing</a>
                    <a href="jobs.php">Consulting</a>
                    </div>
                    <div>
                    <h4>Resources</h4>
                    <a href="about.php">About Us</a>
                    <a href="privacy.php">Privacy Policy</a>
                    </div>
                </div>
            </div>
        </div>
            <h2 class="section-headline">
                <a href="https://github.com/ShaanPanchal/COS10026-GroupG06.git" target="_blank">GitHub</a>
            </h2>
            <br>
            <h2 class="section-headline">
                <a href="https://neevenemmanuel.atlassian.net/jira/software/projects/WWTP/summary?atlOrigin=eyJpIjoiOWM1ZjBkZWRkOWJmNGZhM2FlZjE3ZTYyMTRkMjI2MzAiLCJwIjoiaiJ9" target="_blank">Jira</a>
            </h2>
        </div>
        <div class="footer-bottom">
            <p>&copy; 2025 SRN Careers. All rights reserved.</p>
        </div>
    </footer>
</body>
</html>