    <!-- Footer -->
    <footer class="main-footer">
        <div class="footer-container">
            <div class="footer-logo">
                <img src="images/logo.png" alt="SRN Careers Logo" width="80">
            </div>
            <div class="footers-links">
                <div class="footer-section">
                    <div>
                    <h4>Services</h4>
                    <a href="jobs.php">Executive Search</a>
                    <a href="jobs.php">Contract Staffing</a>
                    <a href="jobs.php">Consulting</a>
                    </div>
                    <div>
                    <h4>Resources</h4>
                    <a href="about.php">About Us</a>
                    <a href="privacy.php">Privacy Policy</a>
                    </div>
                </div>
            </div>
            <div class="footer-extras">
  <div class="footer-left">
    <a href="https://github.com/..." target="_blank">GitHub</a>
  </div>
  <div class="footer-right">
    <a href="https://neevenemmanuel.atlassian.net/..." target="_blank">Jira</a>
  </div>
</div>
<hr class="footer-line">
<div class="footer-bottom">
  <span>&copy;2025 SRN Careers | All rights reserved.</span>
  <span> Swinburne University of technology </span>
</div>
    </footer>
</body>
</html>